### ISSUE TITLE
Octolapse?

### ISSUE THREAD

**Issue by ElDavoo** [jneilliii/OctoPrint-TimelapsePurger#1]
Hello,
does this plugin purge OctoLapse timelapses?
Thanks

**Comment by jneilliii** [comment]
I'm not sure as I don't use that plugin. Do you happen to know where they are saved on the filesystem?

**Comment by ElDavoo** [comment]
no idea. i will just try and see if it works in a few days

**Comment by ElDavoo** [comment]
Looks like it's not working. I set 1 day in settings and:
```
find /home/pi/.octoprint/timelapse/*.mp4 -type f -mtime 3 | wc -l
3
```

**Comment by jneilliii** [comment]
that's odd because the folder you list is what the plugin loops through [here](https://github.com/jneilliii/OctoPrint-TimelapsePurger/blob/32da6ac55a6636ed837e622110e58d3bc8038d7c/octoprint_timelapsepurger/__init__.py#L24). Enable debug logging for the plugin in OctoPrint's Logging settings at the bottom and let's try to figure out why. The process runs on OctoPrint startup and when the built-in timelapse events are triggered. Might need to do something special for OctoLapse if it's not triggering the same MovieDone event.

**Comment by jneilliii** [comment]
That would actually be a good test. if you restart OctoPrint does the older timelapse files get cleared out?

**Comment by ElDavoo** [comment]
> when the built-in timelapse events are triggered

That's the culprit: OctoLapse generates different events.

**Comment by jneilliii** [comment]
Yeah, notice that. I'll have an update tonight that incorporates its custom events.

**Comment by jneilliii** [comment]
Was able to make the changes during my lunch break. You can force check for updates in Software Update of OctoPrint settings and get version 0.1.3.

**Comment by ElDavoo** [comment]
Thank you very much!
